# Generated by Django 4.1.7 on 2025-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_guest_created_at_guest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
