# Generated by Django 4.1.7 on 2025-05-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_alter_guest_unlimited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='catering.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='catering.guest'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='catering.meal'),
        ),
    ]
