FROM python:3.10-slim


COPY requirements.txt /etc/
RUN pip install -r /etc/requirements.txt

#RUN apt-get update && apt-get install -y default-libmysqlclient-dev build-essential && apt-get clean && pip install mysqlclient==2.1.1
RUN apt-get update && apt-get install -y libpango-1.0-0 libpangoft2-1.0-0
RUN pip install mysql-connector-python==8.0.33 

COPY src /srv/app

EXPOSE 8000
CMD ["/srv/app/runserver.sh"]

