# Generated by Django 4.1.7 on 2024-05-04 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catering', '0002_alter_meal_checked_qty_alter_meal_planned_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printing.category')),
                ('catering_guest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.guest')),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
