# Generated by Django 4.1.7 on 2025-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_category_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
